CREATE TABLE relations(
    USER_ID INT UNSIGNED not null,
    FRIEND_URI varchar(255) NOT NULL,PRIMARY KEY (FRIEND_URI),
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY  (FRIEND_URI) REFERENCES friendlog(FRIEND_URI)
)ENGINE=INNODB;